練習課題３提出
MunehiroMachida/quelcode-php pull request #3
Opened 2020-05-25 12:15 UTC by MunehiroMachida

練習課題３の提出です。
よろしくお願いします

2020-05-26 02:58 UTC, choimake reviewed
動作要件を満たしており良くできています。

いくつかコードの書き方で修正して欲しいところがあるので対応お願いします。

2020-05-26 02:58 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    $dsn = 'mysql:dbname=test;host=mysql';
この場合はif文で数値判定を行い、無効な値だった場合はその場でプログラムを終了させる書き方の方がコードの可読性が高いです。
（長いelse文は大体読みにくい）

```
if($limit <= 0 or $limit != (integer)$limit or $limit != is_numeric($limit)){
    http_response_code(400);
    // エラーの瞬間に処理を終了させる。この書き方だとエラーの後に、以下の処理が間違って実行されている可能性を排除できる。
    exit();
}

(以下に続きの処理を書く)
```

2020-05-26 02:58 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    }
データベース接続エラーの際もプログラムを終了させるようにしてみてください。
動作要件には書いてませんでしたが、一般的なAPIでは普通に実装します。
また適切なエラーコードは是非自分で調べて実装してみましょう。

2020-05-26 02:58 UTC, choimake commented on html/php-pre-challenge3/index.php
> +            }
インデントの深さがズレています。コード全体を通じてインデントのサイズや深さは揃えましょう。

2020-05-26 02:58 UTC, choimake commented on html/php-pre-challenge3/index.php
> +            $array_box = array_merge($array_box,$temps);
ここのelseifの判定は不要に見えます。
最初のif文で配列が空かどうか判定は終わっているので、elseにきた段階で配列が空のデータは存在しないはずです。

2020-05-26 03:00 UTC, choimake reviewed
追加です。

2020-05-26 03:00 UTC, choimake commented on html/php-pre-challenge3/index.php
> +            if($digit == 1){
値を比較する時は「==」ではなく「===」を使うようにしてください。
型を意識したプログラミングができるようになりましょう。

2020-05-26 03:01 UTC, choimake reviewed
追加です。

2020-05-26 03:01 UTC, choimake commented on html/php-pre-challenge3/index.php
> +                    foreach($ts as $t){
記号の間にスペースが入っていたり、入っていなかったりする書き方がまざっています。
どちらのスタイルでも構いませんが、どちらかのスタイルに決め、コード全体で統一してください。

2020-05-26 03:32 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    }
接続エラーの部分を変数に入れ
exitで終了させました。

2020-05-26 03:33 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    $dsn = 'mysql:dbname=test;host=mysql';
ご指摘ありがとうございます。

見えないところで処理されているんですね。クセづけるようにします

2020-05-26 03:38 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +            }
foreachの中身を修正

2020-05-26 03:47 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +            if($digit == 1){
ご指摘ありがとうございます。
61行目も同じように == が入っていたので処理をする前に
`$limit = (int)$limit;`
として、数値にしてました。

2020-05-26 03:58 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +                    foreach($ts as $t){
全体的に、バラバラでした。以後、気をつけます。

2020-05-26 04:29 UTC, choimake reviewed
前回のレビューの指摘漏れに当たる部分になります。
動作要件に明確に書かれておらず申し訳ありませんが、
「1.0」のような小数の値がtargetで設定された場合エラーを返すという仕様で実装して欲しいです。
現在の実装だと、1.0だとのようなキリのいい小数の値の場合、処理が正常に続行される動作になっているので、エラーになるように修正してください。
（カリキュラムに「1.0」のような値はエラーで実装するようにとの旨を追記いたしました）

2020-05-26 04:29 UTC, choimake commented on html/php-pre-challenge3/index.php
> +        exit($DB_error);
**エラーコード**を返却する処理になっていません。

2020-05-26 04:29 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    }
インデントがズレています。

2020-05-26 07:47 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +        exit($DB_error);
> 現在の実装だと、1.0だとのようなキリのいい小数の値の場合、処理が正常に続行される動作になっているので、エラーになるように修正してください。
  
こちら
```
if(strpos($limit,'.0')){
    http_response_code(400);
    exit();
}
```
を追加し、.0になっている場合、処理を止めるようにしました。

> エラーコードを返却する処理になっていません。

http_response_code(404);
を追加しました。404にした理由は
https://developer.mozilla.org/ja/docs/Web/HTTP/Status/404
で、

> サーバーがリクエストされたリソースを見つけることができない時のクライアントエラーのレスポンスコードです。

クライアント側のエラーだと思い、そうしました

2020-05-26 07:47 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    }
}
の前のスペースを無くしました。

2020-05-27 00:49 UTC, himaru-jp requested changes
確認をお願いします。

2020-05-27 00:49 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +        }
$array_boxは空配列で宣言されているので、
```
$array_box = [];
```
の時にも、
```
array_merge($array_box,$temps);
```
がエラーなく実行できると思います。

if文で処理を分岐する必要はなさそうです。

2020-05-27 00:49 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +if(strpos($limit,'.0')){
4行目は9行目のif文ですが、判定を分けた明確な理由がなければ一つで良いと思います。
ifが長くて読みにくい場合は、判定の途中で改行することもできます。
```
if ($limit <= 0
    or $limit != (integer)$limit
    or $limit != is_numeric($limit)) {
```

2020-05-27 00:49 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    $limit = (int)$limit;
(修正は不要)
キャスト(型変換)の書き方が行によって異なります。
どちらも同じ動作になるのですが、同じプログラムでは統一すると見やすくなります！
```
(integer)$limit
(int)$record[$i]['value'];
(int)$limit;
```

2020-05-27 00:49 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    echo'</pre>';
print_rは変数の情報を分かりやすく表示するための関すです。
「JOSN形式で出力」という要件の場合は、echoで出力してください。
またpreタグを出力してしまうと、それはHTML形式となってしまいます。
純粋にJSONのみを出力するようにしてみてください。

以下の二点について調べてみてください
・JSON形式で出力
・print_rとechoの違い

2020-05-27 00:49 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +        }
for全体のインデントが一つずれています。
```suggestion
    $array_amount = count($record);
    for($i = 0; $i < $array_amount; $i++){
        $record_array[] = (int)$record[$i]['value'];
    }
```

2020-05-27 00:49 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    $sum_limit_json = json_encode($sum_limit);
組み合わせが見つからなかったパターンでエラーになります。
また、要件通り組み合わせが見つからなかった場合は、`[]`で出力するように修正をお願いします。

2020-05-27 00:49 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +        for($j = 0; $j < count($array_box[$i]); $j++){
内側のforは不要だと思います。($jにアクセスしてない)
「組み合わせ」がtargetの値と等しいか確認するのに何回ループを回す必要があるか考えてみてください。

2020-05-27 03:05 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +        }
if文、削除しました。

2020-05-27 03:05 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +if(strpos($limit,'.0')){
どうやって、１つにまとめるかが、なぜか昨日は
思いつきませんでした。

後ろにorを足してまとめました。

2020-05-27 03:06 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    $limit = (int)$limit;
以後気をつけます。

2020-05-27 03:22 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    echo'</pre>';
・JSON形式で出力
┗ javascriptの連想配列なんですね。

printは『式』。echoは『式』ではない。と難しいやつが出てきました。
とりあえず、printはカンマで区切って文字列の出力ができない。というのがわかりました。
こういう、何気なく使っているのも意識します。


echo'<pre>';を消して    echo($sum_limit_json);にしました。

2020-05-27 04:02 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    $sum_limit_json = json_encode($sum_limit);
is_nullをつけて組み合わせがない場合は[]を出力するようにしました。

2020-05-27 04:11 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +        for($j = 0; $j < count($array_box[$i]); $j++){
> 「組み合わせ」がtargetの値と等しいか確認するのに何回ループを回す必要があるか考えてみてください。

配列の数分(255回)、回しているので内側のループは不要でした。すみません。

2020-05-27 04:20 UTC, himaru-jp requested changes
確認をお願いします。

2020-05-27 04:20 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    if(is_null($sum_limit)){
$sum_limitが宣言されていないため、この場合も組み合わせがない場合はエラーになります。
組み合わせがないパターンのテストを実施してみてください。
例 `?target=2`

2020-05-27 04:20 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    if(is_null($sum_limit)){
ifで分岐するのではなく、事前に$sum_limitを宣言しておくといいと思います。

2020-05-27 04:23 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    http_response_code(400);
サーバ側の問題の場合は、ステータスコード400は不適切です。
HTTPステータスコードについて調べてみて、適切だと思うものに書き換えてみてください。

2020-05-27 05:39 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    if(is_null($sum_limit)){
62行目、$limit = (int)$limit;の後に
$sum_limit = [];
を足しました。

そしたら、からの配列のまま、jsonに変換されました。
1時間くらい悩みました。

2020-05-27 05:51 UTC, MunehiroMachida commented on html/php-pre-challenge3/index.php
> +    http_response_code(400);
HTTPステータスコード　500にしました。
理由としては、サーバー内部のエラーだと思いました。

400にしていた理由はリクエストにエラーがあると思っていたからです。

考えてみたら、サーバーサイド側(PHP)で勝手にエラーにしてるだけですので
リクエストのエラーではないですよね。ご指摘ありがとうございます。

もし、解釈が間違っていたら、また教えていただきたいです。

2020-05-27 06:33 UTC, himaru-jp approved these changes
LGTM！

修正不要ですが、参考までにいくつかコメントしました。

できるだけ変数に意味を持たせるようにしてください。
sum_limitやarray_boxなどはソースコードを追わないと何が入っているか想像ができません。
例えば、array_boxであれば、組み合わせが入っているのでcombinationsと命名できるかもしれません。
もっと良い命名がないか是非検討してみてください！次の課題ではその辺りも意識して取り組んでいただけると嬉しいです。

2020-05-27 06:33 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    $record = $records->fetchAll(PDO::FETCH_ASSOC);
(修正不要)
何が入っているか想像しやすい変数名にできるとより良いコードになります！
```suggestion
    $pdo = $db->query('SELECT value FROM prechallenge3');
    $records = $records->fetchAll(PDO::FETCH_ASSOC);
```

2020-05-27 06:33 UTC, himaru-jp commented on html/php-pre-challenge3/index.php
> +    for($i = 0; $i < $array_amount; $i++){
(修正不要)
foreachでループするとよりシンプルなコード になります。
foreachで調べて、使ってみてください。

2020-05-28 04:06 UTC, merged